name: Auto-merge

on:
  pull_request:
    types: [labeled, synchronize]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge-ok')
    
    steps:
    - name: Wait for cooldown
      if: github.event.action == 'labeled'
      run: sleep 1800  # 30 minutes
    
    - name: Check PR size
      uses: actions/github-script@v6
      with:
        script: |
          const pr = context.payload.pull_request;
          const { data: prData } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.number
          });
          
          if (prData.additions > 200) {
            core.setFailed(`PR has ${prData.additions} additions, exceeds 200 LOC limit`);
          }
    
    - name: Auto-merge
      uses: pascalgn/merge-action@v0.15.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        method: squash